#:schema https://raw.githubusercontent.com/JanDeDobbeleer/oh-my-posh/main/themes/schema.json

version = 2
final_space = true

[[blocks]]
  type = 'prompt'
  alignment = 'left'
  newline = true

  [[blocks.segments]]
    type = 'path'
    style = 'plain'
    background = 'transparent'
    foreground = 'cyan'
    template = '<b>{{ .Path }}</b>'

    [blocks.segments.properties]
      style = 'folder'

  [[blocks.segments]]
    type = 'git'
    style = 'plain'
    background = 'transparent'
    foreground_templates = [
      "{{ if or (.Working.Changed) (.Staging.Changed) }}yellow{{ end }}",
      "{{ if or (gt .Ahead 0) (gt .Behind 0) }}yellow{{ end }}",
      "{{ if gt .Ahead 0 }}blue{{ end }}",
      "{{ if gt .Behind 0 }}blue{{ end }}",
      "{{ if .Detached }}red{{ end }}",
      "{{ if .Merge }}red{{ end }}",
      "{{ if .CherryPick }}red{{ end }}",
      "{{ if .Revert }}red{{ end }}",
      "magenta"
    ]
    template = ' <b>{{ .HEAD }}{{ if or (.Working.Changed) (.Staging.Changed) }} <red>[{{ if (gt .Working.Untracked 0) }}?{{ end }}{{ if (gt .Working.Modified 0) }}!{{ end }}{{ if .Staging.Changed }}+{{ end }}{{ if .Merge }}={{ end }}]</>{{ end }}</b>'

    [blocks.segments.properties]
      commit_icon = '@'
      fetch_status = true

[[blocks]]
  type = 'rprompt'
  overflow = 'hidden'

  [[blocks.segments]]
    type = 'executiontime'
    style = 'plain'
    foreground = 'yellow'
    background = 'transparent'
    template = '<b>{{ .FormattedMs }}</b>'

[[blocks]]
  type = 'prompt'
  alignment = 'left'
  newline = true

  [[blocks.segments]]
    type = 'text'
    style = 'plain'
    foreground_templates = [
      "{{if gt .Code 0}}red{{end}}",
      "{{if eq .Code 0}}green{{end}}",
    ]
    background = 'transparent'
    template = '❯'

[transient_prompt]
  foreground_templates = [
    "{{if gt .Code 0}}red{{end}}",
    "{{if eq .Code 0}}green{{end}}",
  ]
  background = 'transparent'
  template = '❯'
