# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  modulesPath,
  ...
}:

{
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot.initrd.availableKernelModules = [
    "ahci"
    "xhci_pci"
    "uas"
    "sd_mod"
    "sdhci_pci"
  ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" = {
    device = "/dev/disk/by-uuid/502f5c52-a712-419e-8e97-23ea9c45a337";
    fsType = "ext4";
  };

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/46E6-262C";
    fsType = "vfat";
    options = [
      "fmask=0077"
      "dmask=0077"
    ];
  };

  swapDevices = [ ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.br-341dd931110e.useDHCP = lib.mkDefault true;
  # networking.interfaces.br-6998e282127f.useDHCP = lib.mkDefault true;
  # networking.interfaces.docker0.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp2s0.useDHCP = lib.mkDefault true;
  # networking.interfaces.tailscale0.useDHCP = lib.mkDefault true;
  # networking.interfaces.veth1017302.useDHCP = lib.mkDefault true;
  # networking.interfaces.veth14328d2.useDHCP = lib.mkDefault true;
  # networking.interfaces.veth208faf7.useDHCP = lib.mkDefault true;
  # networking.interfaces.veth20a4a58.useDHCP = lib.mkDefault true;
  # networking.interfaces.veth2a609e1.useDHCP = lib.mkDefault true;
  # networking.interfaces.veth2c14bab.useDHCP = lib.mkDefault true;
  # networking.interfaces.veth3836cac.useDHCP = lib.mkDefault true;
  # networking.interfaces.veth390e3b6.useDHCP = lib.mkDefault true;
  # networking.interfaces.veth418adb0.useDHCP = lib.mkDefault true;
  # networking.interfaces.veth491d1c1.useDHCP = lib.mkDefault true;
  # networking.interfaces.veth4cba072.useDHCP = lib.mkDefault true;
  # networking.interfaces.veth4f039cf.useDHCP = lib.mkDefault true;
  # networking.interfaces.veth5655581.useDHCP = lib.mkDefault true;
  # networking.interfaces.veth59df5ef.useDHCP = lib.mkDefault true;
  # networking.interfaces.veth647bd76.useDHCP = lib.mkDefault true;
  # networking.interfaces.veth74a1ba1.useDHCP = lib.mkDefault true;
  # networking.interfaces.veth7db7fc7.useDHCP = lib.mkDefault true;
  # networking.interfaces.veth85c7dd4.useDHCP = lib.mkDefault true;
  # networking.interfaces.veth8c1c88c.useDHCP = lib.mkDefault true;
  # networking.interfaces.veth93c4967.useDHCP = lib.mkDefault true;
  # networking.interfaces.vetha4115da.useDHCP = lib.mkDefault true;
  # networking.interfaces.vethb0881a6.useDHCP = lib.mkDefault true;
  # networking.interfaces.vethb7d3c63.useDHCP = lib.mkDefault true;
  # networking.interfaces.vethd6833cb.useDHCP = lib.mkDefault true;
  # networking.interfaces.vethdb506b7.useDHCP = lib.mkDefault true;
  # networking.interfaces.vethe3c8a62.useDHCP = lib.mkDefault true;
  # networking.interfaces.vethe9d42b7.useDHCP = lib.mkDefault true;
  # networking.interfaces.vethec764e5.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
  boot.swraid.enable = true;

}
