# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "ahci" "xhci_pci" "uas" "sd_mod" "sdhci_pci" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/502f5c52-a712-419e-8e97-23ea9c45a337";
      fsType = "ext4";
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/46E6-262C";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  fileSystems."/mnt/External" =
    { device = "/dev/disk/by-uuid/9a5cdc5e-362f-eb4e-9f9a-8ca6ed0d6671";
      fsType = "ext4";
      options = [ "rw" "user" "nofail" ];
    };

  swapDevices = [ ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.br-5ba0cf04bb33.useDHCP = lib.mkDefault true;
  # networking.interfaces.br-714ef4c1c4e3.useDHCP = lib.mkDefault true;
  # networking.interfaces.br-87fa93f1a59a.useDHCP = lib.mkDefault true;
  # networking.interfaces.docker0.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp2s0.useDHCP = lib.mkDefault true;
  # networking.interfaces.tailscale0.useDHCP = lib.mkDefault true;
  # networking.interfaces.veth0fb3955.useDHCP = lib.mkDefault true;
  # networking.interfaces.veth2964daa.useDHCP = lib.mkDefault true;
  # networking.interfaces.veth3516761.useDHCP = lib.mkDefault true;
  # networking.interfaces.veth3bf2b01.useDHCP = lib.mkDefault true;
  # networking.interfaces.veth42e439b.useDHCP = lib.mkDefault true;
  # networking.interfaces.veth4758224.useDHCP = lib.mkDefault true;
  # networking.interfaces.veth55267f2.useDHCP = lib.mkDefault true;
  # networking.interfaces.veth7e10d8e.useDHCP = lib.mkDefault true;
  # networking.interfaces.veth865a1c8.useDHCP = lib.mkDefault true;
  # networking.interfaces.veth8f6af6c.useDHCP = lib.mkDefault true;
  # networking.interfaces.veth9da259b.useDHCP = lib.mkDefault true;
  # networking.interfaces.vethafdebb3.useDHCP = lib.mkDefault true;
  # networking.interfaces.vethb2971f7.useDHCP = lib.mkDefault true;
  # networking.interfaces.vethb6ba345.useDHCP = lib.mkDefault true;
  # networking.interfaces.vethbf80a2e.useDHCP = lib.mkDefault true;
  # networking.interfaces.vethfe7c368.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
